name: humans_or_horses
description: "El clasificador de imágenes de humanos o caballos"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  hugeicons: ^0.0.11
  image: ^4.5.4
  image_picker: ^1.1.2
  tflite_flutter: ^0.11.0

dev_dependencies:
  flutter_launcher_icons: null
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

# Generate launcher icons settings
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/app_logo_squared.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/app_logo_squared.png"
  min_sdk_android: 24 # android min sdk min:16, default 21

flutter_assets:
  assets_path: assets/
  output_path: lib/presentation/constants/
  filename: assets.dart

flutter:
  uses-material-design: true

  assets:
    - assets/
